apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "service.name" . }}-{{ .Release.Namespace }}
  namespace: istio-system
spec:
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect