---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dstrategies-frontend-{{ .Release.Namespace }}
  namespace: istio-system
spec:
  host: dstrategies-frontend-{{ .Release.Namespace }}-istio-system.apps.{{ .Values.domain }}
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http2

