apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "service.name" . }}-{{ .Release.Namespace }}
  namespace: istio-system
spec:
  host: {{ include "service.name" . }}-{{ .Release.Namespace }}-istio-system.apps.{{ .Values.domain }}
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http2